/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.multiplos.apresentacao;

/**
 *
 * @author Rever
 */
public class frmPrincipal extends javax.swing.JDialog
{

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mnbCalculos = new javax.swing.JMenuBar();
        mnuCalculos = new javax.swing.JMenu();
        mniPrimo = new javax.swing.JMenuItem();
        mniTriangulos = new javax.swing.JMenuItem();
        mniFatorial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mnuCalculos.setText("Calculos");

        mniPrimo.setText("Primo");
        mniPrimo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniPrimoActionPerformed(evt);
            }
        });
        mnuCalculos.add(mniPrimo);

        mniTriangulos.setText("Triangulos");
        mniTriangulos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniTriangulosActionPerformed(evt);
            }
        });
        mnuCalculos.add(mniTriangulos);

        mniFatorial.setText("Fatorial");
        mniFatorial.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniFatorialActionPerformed(evt);
            }
        });
        mnuCalculos.add(mniFatorial);

        mnbCalculos.add(mnuCalculos);

        setJMenuBar(mnbCalculos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniPrimoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniPrimoActionPerformed
    {//GEN-HEADEREND:event_mniPrimoActionPerformed
        frmPrimo frmP = new frmPrimo(null, true);
        this.setVisible(false);
        frmP.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_mniPrimoActionPerformed

    private void mniTriangulosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniTriangulosActionPerformed
    {//GEN-HEADEREND:event_mniTriangulosActionPerformed
        frmTriangulos frmT = new frmTriangulos(null, true);
        frmT.setVisible(true);
    }//GEN-LAST:event_mniTriangulosActionPerformed

    private void mniFatorialActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniFatorialActionPerformed
    {//GEN-HEADEREND:event_mniFatorialActionPerformed
        frmFatorial frmF = new frmFatorial(null, true);
        frmF.setVisible(true);
    }//GEN-LAST:event_mniFatorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mnbCalculos;
    private javax.swing.JMenuItem mniFatorial;
    private javax.swing.JMenuItem mniPrimo;
    private javax.swing.JMenuItem mniTriangulos;
    private javax.swing.JMenu mnuCalculos;
    // End of variables declaration//GEN-END:variables
}
